const actionTypes = {
  DELETE_TASK: "DELETE_TASK",
  DELETE_TASK_ALL: "DELETE_TASK_ALL",

  REQUEST_TASKS_DATA: "REQUEST_TASKS_DATA",
  REQUEST_TASKS_DATA_SUCCESS: "REQUEST_TASKS_DATA_SUCCESS",
  REQUEST_TASKS_DATA_ERROR: "REQUEST_TASKS_DATA_ERROR",

  SET_INPUT_VAL: "SET_INPUT_VAL",
  SET_TASKS_DATA: "SET_TASKS_DATA",

  SET_TASKS_LOADING: "SET_TASKS_LOADING", // change loading to true/false
  SET_TASKS_ERROR: "SET_TASKS_ERROR", //change error to true or false
};

export { actionTypes };
